"""add inbox

Revision ID: 0a656338fbe8
Revises: 6af3b84eaa5e
Create Date: 2026-02-08 17:23:58.236692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a656338fbe8'
down_revision = '6af3b84eaa5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'counterparty_expense_rules',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_pk', sa.Integer(), nullable=False),
        sa.Column('counterparty_key', sa.String(length=255), nullable=False),
        sa.Column('rule', sa.String(length=16), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint("rule IN ('business','personal')", name='ck_exp_rules_rule'),
        sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_pk', 'counterparty_key', name='uq_exp_rules_user_counterparty')
    )
    with op.batch_alter_table('counterparty_expense_rules', schema=None) as batch_op:
        batch_op.create_index('idx_exp_rules_user_active', ['user_pk', 'active'], unique=False)

    op.create_table(
        'dashboard_snapshots',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_pk', sa.Integer(), nullable=False),
        sa.Column('month_key', sa.String(length=7), nullable=False),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboard_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_snap_user_month', ['user_pk', 'month_key'], unique=False)

    op.create_table(
        'settings',
        sa.Column('user_pk', sa.Integer(), nullable=False),
        sa.Column('default_tax_rate', sa.Float(), nullable=False),
        sa.Column('custom_rates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ),
        sa.PrimaryKeyConstraint('user_pk')
    )

    op.create_table(
        'weekly_tasks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_pk', sa.Integer(), nullable=False),
        sa.Column('week_key', sa.String(length=10), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('kind', sa.String(length=32), nullable=False),
        sa.Column('cta_label', sa.String(length=32), nullable=False),
        sa.Column('cta_url', sa.String(length=255), nullable=False),
        sa.Column('is_done', sa.Boolean(), nullable=False),
        sa.Column('done_at', sa.DateTime(), nullable=True),
        sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_pk', 'week_key', name='uq_weekly_tasks_user_week')
    )
    with op.batch_alter_table('weekly_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_weekly_tasks_user_week', ['user_pk', 'week_key'], unique=False)

    op.create_table(
        'evidence_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_pk', sa.Integer(), nullable=False),
        sa.Column('transaction_id', sa.Integer(), nullable=False),
        sa.Column('requirement', sa.String(length=16), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint("requirement IN ('required','maybe','not_needed')", name='ck_evidence_requirement'),
        sa.CheckConstraint("status IN ('missing','attached','not_needed')", name='ck_evidence_status'),
        sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
        sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.create_index('idx_evidence_user_req', ['user_pk', 'requirement'], unique=False)
        batch_op.create_index('idx_evidence_user_status', ['user_pk', 'status'], unique=False)

    op.create_table(
        'expense_labels',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_pk', sa.Integer(), nullable=False),
        sa.Column('transaction_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('confidence', sa.Integer(), nullable=False),
        sa.Column('labeled_by', sa.String(length=8), nullable=False),
        sa.Column('rule_version', sa.Integer(), nullable=False),
        sa.Column('decided_at', sa.DateTime(), nullable=True),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint("labeled_by IN ('auto','user')", name='ck_expense_labels_labeled_by'),
        sa.CheckConstraint("status IN ('business','personal','mixed','unknown')", name='ck_expense_labels_status'),
        sa.CheckConstraint('confidence BETWEEN 0 AND 100', name='ck_expense_labels_confidence'),
        sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
        sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('expense_labels', schema=None) as batch_op:
        batch_op.create_index('idx_expense_labels_user_status', ['user_pk', 'status'], unique=False)

    with op.batch_alter_table('safe_to_spend_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safe_to_spend_settings_created_at'))
        batch_op.drop_index(batch_op.f('ix_safe_to_spend_settings_updated_at'))
    op.drop_table('safe_to_spend_settings')

    with op.batch_alter_table('counterparty_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counterparty_rules_created_at'))
        batch_op.drop_index(batch_op.f('ix_counterparty_rules_updated_at'))
        batch_op.drop_index(batch_op.f('ix_counterparty_rules_user_pk'))

    # ----------------------------
    # dashboard_entries (FIX: 기존 row 때문에 NOT NULL 추가가 터짐)
    # ----------------------------
    with op.batch_alter_table('dashboard_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=16), nullable=True, server_default=sa.text("'income'")))
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True, server_default=sa.text("0")))
        batch_op.add_column(sa.Column('note', sa.String(length=255), nullable=True))

    op.execute("""
        UPDATE dashboard_entries
        SET
          kind = CASE
            WHEN COALESCE(exp, 0) <> 0 THEN 'expense'
            WHEN COALESCE(rev, 0) <> 0 THEN 'income'
            ELSE 'income'
          END,
          amount = CASE
            WHEN COALESCE(exp, 0) <> 0 THEN COALESCE(exp, 0)
            WHEN COALESCE(rev, 0) <> 0 THEN COALESCE(rev, 0)
            ELSE 0
          END,
          note = COALESCE(note, memo)
        WHERE kind IS NULL OR amount IS NULL OR note IS NULL
    """)

    with op.batch_alter_table('dashboard_entries', schema=None) as batch_op:
        batch_op.alter_column('kind', existing_type=sa.String(length=16), nullable=False, server_default=None)
        batch_op.alter_column('amount', existing_type=sa.Integer(), nullable=False, server_default=None)

        batch_op.drop_index(batch_op.f('idx_dashboard_entries_user_time'))
        batch_op.drop_index(batch_op.f('ix_dashboard_entries_created_at'))
        batch_op.drop_index(batch_op.f('ix_dashboard_entries_updated_at'))
        batch_op.drop_index(batch_op.f('ix_dashboard_entries_user_pk'))
        batch_op.create_index('idx_dash_entries_user_created', ['user_pk', 'created_at'], unique=False)

        batch_op.drop_column('safe_to_spend')
        batch_op.drop_column('rate')
        batch_op.drop_column('reserve_amount')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('memo')
        batch_op.drop_column('rev')
        batch_op.drop_column('exp')

    # ----------------------------
    # hold_decisions (FIX: 기존 row 있을 수 있음 → NOT NULL 컬럼 추가 안전하게)
    # ----------------------------
    with op.batch_alter_table('hold_decisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_krw', sa.Integer(), nullable=True, server_default=sa.text("0")))
        batch_op.add_column(sa.Column('rate', sa.Float(), nullable=True, server_default=sa.text("0.0")))
        batch_op.add_column(sa.Column('reason', sa.String(length=32), nullable=True, server_default=sa.text("'unknown'")))

    # 기존 컬럼에서 최대한 백필 (있으면 보존)
    op.execute("""
        UPDATE hold_decisions
        SET
          amount_krw = COALESCE(amount_krw, confirmed_amount_krw, recommended_amount_krw, 0),
          rate = COALESCE(rate, rate_applied, 0),
          reason = COALESCE(reason, preset, 'unknown')
        WHERE amount_krw IS NULL OR rate IS NULL OR reason IS NULL
    """)

    with op.batch_alter_table('hold_decisions', schema=None) as batch_op:
        batch_op.alter_column('amount_krw', existing_type=sa.Integer(), nullable=False, server_default=None)
        batch_op.alter_column('rate', existing_type=sa.Float(), nullable=False, server_default=None)
        batch_op.alter_column('reason', existing_type=sa.String(length=32), nullable=False, server_default=None)

        batch_op.drop_index(batch_op.f('idx_hold_user_created'))
        batch_op.drop_index(batch_op.f('idx_hold_user_status'))
        batch_op.drop_index(batch_op.f('ix_hold_decisions_created_at'))
        batch_op.drop_index(batch_op.f('ix_hold_decisions_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_hold_decisions_user_pk'))
        batch_op.drop_constraint(batch_op.f('hold_decisions_transaction_id_fkey'), type_='foreignkey')

        batch_op.drop_column('rate_applied')
        batch_op.drop_column('rationale')
        batch_op.drop_column('confirmed_amount_krw')
        batch_op.drop_column('recommended_amount_krw')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('status')
        batch_op.drop_column('ytd_income_krw')
        batch_op.drop_column('preset')
        batch_op.drop_column('confirmed_at')

    # ----------------------------
    # import_jobs (FIX: 기존 row 있으면 created_at NOT NULL 추가에서 터짐)
    # ----------------------------
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text("NOW()")))

    op.execute("""
        UPDATE import_jobs
        SET created_at = COALESCE(created_at, started_at, NOW())
        WHERE created_at IS NULL
    """)

    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DateTime(), nullable=False, server_default=None)

        batch_op.alter_column(
            'source',
            existing_type=sa.VARCHAR(length=16),
            type_=sa.String(length=32),
            existing_nullable=False
        )
        batch_op.alter_column(
            'error_summary',
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            nullable=True
        )
        batch_op.drop_index(batch_op.f('idx_import_jobs_user_time'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_started_at'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_user_pk'))

    with op.batch_alter_table('income_labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_labels_created_at'))
        batch_op.drop_index(batch_op.f('ix_income_labels_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_income_labels_updated_at'))
        batch_op.drop_index(batch_op.f('ix_income_labels_user_pk'))
        batch_op.create_unique_constraint(None, ['transaction_id'])

    with op.batch_alter_table('tax_buffer_ledger', schema=None) as batch_op:
        batch_op.alter_column(
            'delta_amount_krw',
            existing_type=sa.BIGINT(),
            type_=sa.Integer(),
            existing_nullable=False
        )
        batch_op.alter_column(
            'note',
            existing_type=sa.TEXT(),
            type_=sa.String(length=255),
            existing_nullable=True
        )
        batch_op.drop_index(batch_op.f('idx_ledger_user_reason'))
        batch_op.drop_index(batch_op.f('idx_ledger_user_time'))
        batch_op.drop_index(batch_op.f('ix_tax_buffer_ledger_created_at'))
        batch_op.drop_index(batch_op.f('ix_tax_buffer_ledger_decision_id'))
        batch_op.drop_index(batch_op.f('ix_tax_buffer_ledger_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_tax_buffer_ledger_user_pk'))
        batch_op.create_index('idx_ledger_user_created', ['user_pk', 'created_at'], unique=False)
        batch_op.drop_constraint(batch_op.f('tax_buffer_ledger_decision_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tax_buffer_ledger_transaction_id_fkey'), type_='foreignkey')
        batch_op.drop_column('decision_id')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('reason')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column(
            'amount_krw',
            existing_type=sa.BIGINT(),
            type_=sa.Integer(),
            existing_nullable=False
        )
        batch_op.alter_column(
            'counterparty',
            existing_type=sa.TEXT(),
            type_=sa.String(length=255),
            existing_nullable=True
        )
        batch_op.alter_column(
            'source',
            existing_type=sa.VARCHAR(length=16),
            type_=sa.String(length=32),
            existing_nullable=False
        )
        batch_op.alter_column(
            'external_hash',
            existing_type=sa.VARCHAR(length=128),
            type_=sa.String(length=64),
            existing_nullable=False
        )
        batch_op.drop_index(batch_op.f('idx_transactions_user_dir_time'))
        batch_op.drop_index(batch_op.f('idx_transactions_user_time'))
        batch_op.drop_index(batch_op.f('ix_transactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_import_job_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_user_pk'))
        batch_op.drop_constraint(batch_op.f('uq_transactions_user_hash'), type_='unique')
        batch_op.create_index('idx_tx_user_direction', ['user_pk', 'direction'], unique=False)
        batch_op.create_index('idx_tx_user_occurred', ['user_pk', 'occurred_at'], unique=False)
        batch_op.create_unique_constraint('uq_tx_user_hash', ['user_pk', 'external_hash'])

    # ----------------------------
    # user_dashboard_state (FIX: 지금 너가 터진 부분)
    # ----------------------------
    with op.batch_alter_table('user_dashboard_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gross_income', sa.Integer(), nullable=True, server_default=sa.text("0")))
        batch_op.add_column(sa.Column('expenses', sa.Integer(), nullable=True, server_default=sa.text("0")))
        batch_op.add_column(sa.Column('rate', sa.Float(), nullable=True, server_default=sa.text("0.0")))

    # 기존 state(JSONB)에서 키가 있으면 최대한 복구 (없으면 0 유지)
    op.execute("""
        UPDATE user_dashboard_state
        SET
          gross_income = COALESCE(gross_income, NULLIF((state->>'gross_income')::int, NULL), 0),
          expenses = COALESCE(expenses, NULLIF((state->>'expenses')::int, NULL), 0),
          rate = COALESCE(rate, NULLIF((state->>'rate')::double precision, NULL), 0.0)
        WHERE gross_income IS NULL OR expenses IS NULL OR rate IS NULL
    """)

    with op.batch_alter_table('user_dashboard_state', schema=None) as batch_op:
        batch_op.alter_column('gross_income', existing_type=sa.Integer(), nullable=False, server_default=None)
        batch_op.alter_column('expenses', existing_type=sa.Integer(), nullable=False, server_default=None)
        batch_op.alter_column('rate', existing_type=sa.Float(), nullable=False, server_default=None)

        batch_op.drop_index(batch_op.f('ix_user_dashboard_state_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_dashboard_state_updated_at'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('state')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(
            'email',
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=120),
            existing_nullable=False
        )
        batch_op.alter_column(
            'password_hash',
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=256),
            existing_nullable=False
        )
        batch_op.drop_index(batch_op.f('ix_users_birthdate'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_nickname'))
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('birthdate')
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('birthdate', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_nickname'), ['nickname'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_birthdate'), ['birthdate'], unique=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('user_dashboard_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_user_dashboard_state_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_dashboard_state_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('rate')
        batch_op.drop_column('expenses')
        batch_op.drop_column('gross_income')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tx_user_hash', type_='unique')
        batch_op.drop_index('idx_tx_user_occurred')
        batch_op.drop_index('idx_tx_user_direction')
        batch_op.create_unique_constraint(batch_op.f('uq_transactions_user_hash'), ['user_pk', 'external_hash'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_pk'), ['user_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_import_job_id'), ['import_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_transactions_user_time'), ['user_pk', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_transactions_user_dir_time'), ['user_pk', 'direction', 'occurred_at'], unique=False)
        batch_op.alter_column('external_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.alter_column('counterparty',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('amount_krw',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('tax_buffer_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('decision_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('tax_buffer_ledger_transaction_id_fkey'), 'transactions', ['transaction_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('tax_buffer_ledger_decision_id_fkey'), 'hold_decisions', ['decision_id'], ['id'])
        batch_op.drop_index('idx_ledger_user_created')
        batch_op.create_index(batch_op.f('ix_tax_buffer_ledger_user_pk'), ['user_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_buffer_ledger_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_buffer_ledger_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_buffer_ledger_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_ledger_user_time'), ['user_pk', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_ledger_user_reason'), ['user_pk', 'reason'], unique=False)
        batch_op.alter_column('note',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('delta_amount_krw',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('income_labels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_income_labels_user_pk'), ['user_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_labels_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_labels_transaction_id'), ['transaction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_income_labels_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_jobs_user_pk'), ['user_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_import_jobs_user_time'), ['user_pk', 'started_at'], unique=False)
        batch_op.alter_column('error_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('hold_decisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('preset', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ytd_income_krw', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('recommended_amount_krw', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('confirmed_amount_krw', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rationale', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rate_applied', sa.NUMERIC(precision=6, scale=4), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('hold_decisions_transaction_id_fkey'), 'transactions', ['transaction_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_hold_decisions_user_pk'), ['user_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_hold_decisions_transaction_id'), ['transaction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_hold_decisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_hold_user_status'), ['user_pk', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_hold_user_created'), ['user_pk', 'created_at'], unique=False)
        batch_op.drop_column('reason')
        batch_op.drop_column('rate')
        batch_op.drop_column('amount_krw')

    with op.batch_alter_table('dashboard_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exp', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rev', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('memo', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('reserve_amount', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rate', sa.NUMERIC(precision=6, scale=4), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('safe_to_spend', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.drop_index('idx_dash_entries_user_created')
        batch_op.create_index(batch_op.f('ix_dashboard_entries_user_pk'), ['user_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboard_entries_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboard_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_dashboard_entries_user_time'), ['user_pk', 'created_at'], unique=False)
        batch_op.drop_column('note')
        batch_op.drop_column('amount')
        batch_op.drop_column('kind')

    with op.batch_alter_table('counterparty_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counterparty_rules_user_pk'), ['user_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_counterparty_rules_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_counterparty_rules_created_at'), ['created_at'], unique=False)

    op.create_table('safe_to_spend_settings',
    sa.Column('user_pk', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preset', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('rounding_unit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('min_hold_krw', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_hold_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('exclusions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('custom_rates', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], name=op.f('safe_to_spend_settings_user_pk_fkey')),
    sa.PrimaryKeyConstraint('user_pk', name=op.f('safe_to_spend_settings_pkey'))
    )
    with op.batch_alter_table('safe_to_spend_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safe_to_spend_settings_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_safe_to_spend_settings_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('expense_labels', schema=None) as batch_op:
        batch_op.drop_index('idx_expense_labels_user_status')

    op.drop_table('expense_labels')
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.drop_index('idx_evidence_user_status')
        batch_op.drop_index('idx_evidence_user_req')

    op.drop_table('evidence_items')
    with op.batch_alter_table('weekly_tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_weekly_tasks_user_week')

    op.drop_table('weekly_tasks')
    op.drop_table('settings')
    with op.batch_alter_table('dashboard_snapshots', schema=None) as batch_op:
        batch_op.drop_index('idx_snap_user_month')

    op.drop_table('dashboard_snapshots')
    with op.batch_alter_table('counterparty_expense_rules', schema=None) as batch_op:
        batch_op.drop_index('idx_exp_rules_user_active')

    op.drop_table('counterparty_expense_rules')
    # ### end Alembic commands ###
