"""add bank account links

Revision ID: 20fb1ab4f140
Revises: e21922970682
Create Date: 2026-02-13 04:33:42.734778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20fb1ab4f140'
down_revision = 'e21922970682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_account_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('bank_code', sa.String(length=4), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('alias', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_pk', 'bank_code', 'account_number', name='uq_user_bankacct')
    )
    with op.batch_alter_table('bank_account_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_account_links_user_pk'), ['user_pk'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_account_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_account_links_user_pk'))

    op.drop_table('bank_account_links')
    # ### end Alembic commands ###
