"""csv format mapping cache

Revision ID: 25cf30a63ddf
Revises: 4f534039d904
Create Date: 2026-02-22 16:04:28.711495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25cf30a63ddf'
down_revision = '4f534039d904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_format_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delimiter', sa.String(length=4), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_pk', 'signature', name='uq_csv_map_user_sig')
    )
    with op.batch_alter_table('csv_format_mappings', schema=None) as batch_op:
        batch_op.create_index('idx_csv_map_user', ['user_pk'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('csv_format_mappings', schema=None) as batch_op:
        batch_op.drop_index('idx_csv_map_user')

    op.drop_table('csv_format_mappings')
    # ### end Alembic commands ###
