"""add recurring_rules

Revision ID: 2a8843434ed2
Revises: 20fb1ab4f140
Create Date: 2026-02-14 20:06:02.270505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8843434ed2'
down_revision = '20fb1ab4f140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('amount_krw', sa.Integer(), nullable=False),
    sa.Column('counterparty', sa.String(length=255), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('cadence', sa.String(length=16), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("cadence IN ('monthly','weekly')", name='ck_rr_cadence'),
    sa.CheckConstraint("direction IN ('in','out')", name='ck_rr_direction'),
    sa.CheckConstraint('amount_krw >= 0', name='ck_rr_amount_nonneg'),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_rules', schema=None) as batch_op:
        batch_op.create_index('idx_rr_user_active', ['user_pk', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_rules_user_pk'), ['user_pk'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_rules_user_pk'))
        batch_op.drop_index('idx_rr_user_active')

    op.drop_table('recurring_rules')
    # ### end Alembic commands ###
