"""add evidence vault file fields

Revision ID: 4f534039d904
Revises: 2a8843434ed2
Create Date: 2026-02-15 19:19:04.295660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f534039d904'
down_revision = '2a8843434ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_key', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mime_type', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('size_bytes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sha256', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('retention_until', sa.Date(), nullable=True))
        batch_op.create_index('idx_evidence_user_retention', ['user_pk', 'retention_until'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.drop_index('idx_evidence_user_retention')
        batch_op.drop_column('retention_until')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('sha256')
        batch_op.drop_column('size_bytes')
        batch_op.drop_column('mime_type')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('file_key')

    # ### end Alembic commands ###
