"""add dashboard_entries

Revision ID: 6af3b84eaa5e
Revises: 79bda2e37014
Create Date: 2026-02-07 21:41:09.402390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af3b84eaa5e'
down_revision = '79bda2e37014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('memo', sa.String(length=200), nullable=True),
    sa.Column('rev', sa.BigInteger(), nullable=False),
    sa.Column('exp', sa.BigInteger(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('safe_to_spend', sa.BigInteger(), nullable=False),
    sa.Column('reserve_amount', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboard_entries', schema=None) as batch_op:
        batch_op.create_index('idx_dashboard_entries_user_time', ['user_pk', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboard_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboard_entries_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboard_entries_user_pk'), ['user_pk'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_entries_user_pk'))
        batch_op.drop_index(batch_op.f('ix_dashboard_entries_updated_at'))
        batch_op.drop_index(batch_op.f('ix_dashboard_entries_created_at'))
        batch_op.drop_index('idx_dashboard_entries_user_time')

    op.drop_table('dashboard_entries')
    # ### end Alembic commands ###
