"""add user_dashboard_state

Revision ID: 79bda2e37014
Revises: eca9115039cc
Create Date: 2026-02-07 21:06:34.033035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79bda2e37014'
down_revision = 'eca9115039cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_dashboard_state',
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_pk')
    )
    with op.batch_alter_table('user_dashboard_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_dashboard_state_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_dashboard_state_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_dashboard_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_dashboard_state_updated_at'))
        batch_op.drop_index(batch_op.f('ix_user_dashboard_state_created_at'))

    op.drop_table('user_dashboard_state')
    # ### end Alembic commands ###
