"""init db

Revision ID: eca9115039cc
Revises: 
Create Date: 2026-02-06 20:25:46.094369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eca9115039cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_birthdate'), ['birthdate'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_nickname'), ['nickname'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)

    op.create_table('counterparty_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('counterparty_key', sa.String(length=255), nullable=False),
    sa.Column('rule', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("rule IN ('income','non_income')", name='ck_rules_rule'),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_pk', 'counterparty_key', name='uq_rules_user_counterparty')
    )
    with op.batch_alter_table('counterparty_rules', schema=None) as batch_op:
        batch_op.create_index('idx_rules_user_active', ['user_pk', 'active'], unique=False)
        batch_op.create_index(batch_op.f('ix_counterparty_rules_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_counterparty_rules_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_counterparty_rules_user_pk'), ['user_pk'], unique=False)

    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('inserted_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('error_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_import_jobs_user_time', ['user_pk', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_user_pk'), ['user_pk'], unique=False)

    op.create_table('safe_to_spend_settings',
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('preset', sa.String(length=16), nullable=False),
    sa.Column('rounding_unit', sa.Integer(), nullable=False),
    sa.Column('min_hold_krw', sa.Integer(), nullable=False),
    sa.Column('max_hold_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('exclusions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('custom_rates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_pk')
    )
    with op.batch_alter_table('safe_to_spend_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safe_to_spend_settings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_safe_to_spend_settings_updated_at'), ['updated_at'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('import_job_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('amount_krw', sa.BigInteger(), nullable=False),
    sa.Column('counterparty', sa.Text(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('external_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("direction IN ('in','out')", name='ck_transactions_direction'),
    sa.CheckConstraint('amount_krw > 0', name='ck_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_pk', 'external_hash', name='uq_transactions_user_hash')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_transactions_user_dir_time', ['user_pk', 'direction', 'occurred_at'], unique=False)
        batch_op.create_index('idx_transactions_user_time', ['user_pk', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_import_job_id'), ['import_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_pk'), ['user_pk'], unique=False)

    op.create_table('hold_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('preset', sa.String(length=16), nullable=False),
    sa.Column('rate_applied', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('recommended_amount_krw', sa.BigInteger(), nullable=False),
    sa.Column('confirmed_amount_krw', sa.BigInteger(), nullable=False),
    sa.Column('ytd_income_krw', sa.BigInteger(), nullable=False),
    sa.Column('rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('recommended','confirmed','skipped')", name='ck_hold_status'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hold_decisions', schema=None) as batch_op:
        batch_op.create_index('idx_hold_user_created', ['user_pk', 'created_at'], unique=False)
        batch_op.create_index('idx_hold_user_status', ['user_pk', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_hold_decisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hold_decisions_transaction_id'), ['transaction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_hold_decisions_user_pk'), ['user_pk'], unique=False)

    op.create_table('income_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('labeled_by', sa.String(length=8), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("labeled_by IN ('auto','user')", name='ck_income_labels_labeled_by'),
    sa.CheckConstraint("status IN ('income','non_income','unknown')", name='ck_income_labels_status'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 100', name='ck_income_labels_confidence'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('income_labels', schema=None) as batch_op:
        batch_op.create_index('idx_income_labels_user_status', ['user_pk', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_labels_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_labels_transaction_id'), ['transaction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_income_labels_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_labels_user_pk'), ['user_pk'], unique=False)

    op.create_table('tax_buffer_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=16), nullable=False),
    sa.Column('delta_amount_krw', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("reason IN ('income_hold','manual_adjust','rollback','correction')", name='ck_ledger_reason'),
    sa.ForeignKeyConstraint(['decision_id'], ['hold_decisions.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_buffer_ledger', schema=None) as batch_op:
        batch_op.create_index('idx_ledger_user_reason', ['user_pk', 'reason'], unique=False)
        batch_op.create_index('idx_ledger_user_time', ['user_pk', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_buffer_ledger_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_buffer_ledger_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_buffer_ledger_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_buffer_ledger_user_pk'), ['user_pk'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_buffer_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_buffer_ledger_user_pk'))
        batch_op.drop_index(batch_op.f('ix_tax_buffer_ledger_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_tax_buffer_ledger_decision_id'))
        batch_op.drop_index(batch_op.f('ix_tax_buffer_ledger_created_at'))
        batch_op.drop_index('idx_ledger_user_time')
        batch_op.drop_index('idx_ledger_user_reason')

    op.drop_table('tax_buffer_ledger')
    with op.batch_alter_table('income_labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_labels_user_pk'))
        batch_op.drop_index(batch_op.f('ix_income_labels_updated_at'))
        batch_op.drop_index(batch_op.f('ix_income_labels_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_income_labels_created_at'))
        batch_op.drop_index('idx_income_labels_user_status')

    op.drop_table('income_labels')
    with op.batch_alter_table('hold_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hold_decisions_user_pk'))
        batch_op.drop_index(batch_op.f('ix_hold_decisions_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_hold_decisions_created_at'))
        batch_op.drop_index('idx_hold_user_status')
        batch_op.drop_index('idx_hold_user_created')

    op.drop_table('hold_decisions')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_pk'))
        batch_op.drop_index(batch_op.f('ix_transactions_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_import_job_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_created_at'))
        batch_op.drop_index('idx_transactions_user_time')
        batch_op.drop_index('idx_transactions_user_dir_time')

    op.drop_table('transactions')
    with op.batch_alter_table('safe_to_spend_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safe_to_spend_settings_updated_at'))
        batch_op.drop_index(batch_op.f('ix_safe_to_spend_settings_created_at'))

    op.drop_table('safe_to_spend_settings')
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_jobs_user_pk'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_started_at'))
        batch_op.drop_index('idx_import_jobs_user_time')

    op.drop_table('import_jobs')
    with op.batch_alter_table('counterparty_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counterparty_rules_user_pk'))
        batch_op.drop_index(batch_op.f('ix_counterparty_rules_updated_at'))
        batch_op.drop_index(batch_op.f('ix_counterparty_rules_created_at'))
        batch_op.drop_index('idx_rules_user_active')

    op.drop_table('counterparty_rules')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.drop_index(batch_op.f('ix_users_nickname'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.drop_index(batch_op.f('ix_users_birthdate'))

    op.drop_table('users')
    # ### end Alembic commands ###
