from __future__ import annotations

PLAN_FREE = "free"
PLAN_BASIC = "basic"
PLAN_PRO = "pro"
PLAN_VALUES = {PLAN_FREE, PLAN_BASIC, PLAN_PRO}

PROVIDER_TOSS = "toss"

BASIC_PRICE_KRW = 6900
PRO_PRICE_KRW = 12900
ADDON_ACCOUNT_SLOT_PRICE_KRW = 3000
GRACE_DAYS = 3

SYNC_INTERVAL_MINUTES_BY_PLAN: dict[str, int | None] = {
    PLAN_FREE: None,
    PLAN_BASIC: 240,
    PLAN_PRO: 60,
}

ATTEMPT_TYPE_INITIAL = "initial"
ATTEMPT_TYPE_RECURRING = "recurring"
ATTEMPT_TYPE_UPGRADE_FULL_CHARGE = "upgrade_full_charge"
ATTEMPT_TYPE_ADDON_PRORATION = "addon_proration"
ATTEMPT_TYPE_RETRY = "retry"
ATTEMPT_TYPES = {
    ATTEMPT_TYPE_INITIAL,
    ATTEMPT_TYPE_RECURRING,
    ATTEMPT_TYPE_UPGRADE_FULL_CHARGE,
    ATTEMPT_TYPE_ADDON_PRORATION,
    ATTEMPT_TYPE_RETRY,
}

INTENT_TYPE_INITIAL_SUBSCRIPTION = "initial_subscription"
INTENT_TYPE_UPGRADE = "upgrade"
INTENT_TYPE_ADDON_PRORATION = "addon_proration"
CHECKOUT_INTENT_TYPES = {
    INTENT_TYPE_INITIAL_SUBSCRIPTION,
    INTENT_TYPE_UPGRADE,
    INTENT_TYPE_ADDON_PRORATION,
}

CHECKOUT_INTENT_STATUS_CREATED = "created"
CHECKOUT_INTENT_STATUS_REGISTRATION_REQUIRED = "registration_required"
CHECKOUT_INTENT_STATUS_READY_FOR_CHARGE = "ready_for_charge"
CHECKOUT_INTENT_STATUS_CHARGE_STARTED = "charge_started"
CHECKOUT_INTENT_STATUS_COMPLETED = "completed"
CHECKOUT_INTENT_STATUS_FAILED = "failed"
CHECKOUT_INTENT_STATUS_ABANDONED = "abandoned"
CHECKOUT_INTENT_STATUS_CANCELED = "canceled"
CHECKOUT_INTENT_STATUSES = {
    CHECKOUT_INTENT_STATUS_CREATED,
    CHECKOUT_INTENT_STATUS_REGISTRATION_REQUIRED,
    CHECKOUT_INTENT_STATUS_READY_FOR_CHARGE,
    CHECKOUT_INTENT_STATUS_CHARGE_STARTED,
    CHECKOUT_INTENT_STATUS_COMPLETED,
    CHECKOUT_INTENT_STATUS_FAILED,
    CHECKOUT_INTENT_STATUS_ABANDONED,
    CHECKOUT_INTENT_STATUS_CANCELED,
}
CHECKOUT_INTENT_DEFAULT_TTL_MINUTES = 30

SUB_STATUS_PENDING_ACTIVATION = "pending_activation"
SUB_STATUS_ACTIVE = "active"
SUB_STATUS_GRACE_STARTED = "grace_started"
SUB_STATUS_CANCEL_REQUESTED = "cancel_requested"
SUB_STATUS_CANCELED = "canceled"
SUB_STATUS_PAST_DUE = "past_due"
SUBSCRIPTION_STATUSES = {
    SUB_STATUS_PENDING_ACTIVATION,
    SUB_STATUS_ACTIVE,
    SUB_STATUS_GRACE_STARTED,
    SUB_STATUS_CANCEL_REQUESTED,
    SUB_STATUS_CANCELED,
    SUB_STATUS_PAST_DUE,
}

PAYMENT_STATUS_CHARGE_STARTED = "charge_started"
PAYMENT_STATUS_AUTHORIZED = "authorized"
PAYMENT_STATUS_FAILED = "failed"
PAYMENT_STATUS_RECONCILED = "reconciled"
PAYMENT_STATUS_RECONCILE_NEEDED = "reconcile_needed"
PAYMENT_STATUS_CANCELED = "canceled"
PAYMENT_ATTEMPT_STATUSES = {
    PAYMENT_STATUS_CHARGE_STARTED,
    PAYMENT_STATUS_AUTHORIZED,
    PAYMENT_STATUS_FAILED,
    PAYMENT_STATUS_RECONCILED,
    PAYMENT_STATUS_RECONCILE_NEEDED,
    PAYMENT_STATUS_CANCELED,
}

REG_STATUS_STARTED = "registration_started"
REG_STATUS_BILLING_KEY_ISSUED = "billing_key_issued"
REG_STATUS_FAILED = "failed"
REG_STATUS_CANCELED = "canceled"
REGISTRATION_STATUSES = {
    REG_STATUS_STARTED,
    REG_STATUS_BILLING_KEY_ISSUED,
    REG_STATUS_FAILED,
    REG_STATUS_CANCELED,
}

BILLING_METHOD_STATUS_ACTIVE = "active"
BILLING_METHOD_STATUS_REVOKED = "revoked"
BILLING_METHOD_STATUS_INACTIVE = "inactive"
BILLING_METHOD_STATUSES = {
    BILLING_METHOD_STATUS_ACTIVE,
    BILLING_METHOD_STATUS_REVOKED,
    BILLING_METHOD_STATUS_INACTIVE,
}

PAYMENT_EVENT_STATUS_RECEIVED = "received"
PAYMENT_EVENT_STATUS_VALIDATED = "validated"
PAYMENT_EVENT_STATUS_APPLIED = "applied"
PAYMENT_EVENT_STATUS_IGNORED_DUPLICATE = "ignored_duplicate"
PAYMENT_EVENT_STATUS_FAILED = "failed"
PAYMENT_EVENT_STATUSES = {
    PAYMENT_EVENT_STATUS_RECEIVED,
    PAYMENT_EVENT_STATUS_VALIDATED,
    PAYMENT_EVENT_STATUS_APPLIED,
    PAYMENT_EVENT_STATUS_IGNORED_DUPLICATE,
    PAYMENT_EVENT_STATUS_FAILED,
}

SUPPORTED_CURRENCIES = {"KRW"}
